- hosts: target
  become: yes
  tasks:
  - name: Add docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg

  - name: Install basic list of packages
    apt:
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common

  - name: Add apt repository
    apt_repository:
      repo: "deb [arch=amd64,arm64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"

  - name: Install Docker packages
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-buildx-plugin
        - docker-compose-plugin

  - name: Add user to docker group
    user:
      name: "{{ ansible_env.SUDO_USER }}"
      groups: docker
      append: yes

  - name: Ensure docker service is enabled
    systemd:
      name: docker
      state: started
      enabled: yes

